name: Build
on: [push]
env:
  TOOLCHAIN_DOCKER_REPOSITORY: ${{ secrets.DOCKER_ORGANIZATION }}/toolchain
  TOOLCHAIN_TAG: 0.14.0

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dependencies
        run: make toolchain-exec CONTAINER_COMMAND="/usr/bin/make dep -j$(nproc)"

      - name: Build
        run: |
          make toolchain-exec CONTAINER_COMMAND="/usr/bin/make -j$(nproc)"
          make toolchain-exec CONTAINER_COMMAND="/usr/bin/make uarch -j$(nproc)"

      - name: Install
        run: make install

      - name: TAR
        run: tar -czf machine-tests-`git describe --tags --exact-match`.tar.gz -C /opt/cartesi/tests .
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: machine-tests-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
