name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    container: cartesi/toolchain:0.3.0
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}

      - name: Build dependencies
        run: make dep -j$(nproc)

      - name: Build
        run: make -j$(nproc)

      - name: Install
        run: make install

      - name: TAR
        run: tar -czf machine-tests-`git describe --tags --exact-match`.tar.gz -C /opt/cartesi/tests .
        if: startsWith(github.ref, 'refs/tags/v')

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          prerelease: true
          files: machine-tests-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
